In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from matplotlib import pyplot as plt

In [2]:
data = pd.read_csv('/kaggle/input/digit-recognizer/train.csv')

In [3]:
data.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [4]:
data = np.array(data)
m, n = data.shape
np.random.shuffle(data)

data_dev = data[0:1000].T
Y_dev = data_dev[0]   #The labels (target variable) for the development set.
X_dev = data_dev[1:n]   #The features for the development set
X_dev = X_dev / 255.

data_train = data[1000:m].T
Y_train = data_train[0]
X_train = data_train[1:n]
X_train = X_train / 255.
_,m_train = X_train.shape

In [5]:
X_train[:, 0].shape

(784,)

In [6]:
def init_params():
    W1 = np.random.rand(10, 784) - 0.5
    b1 = np.random.rand(10, 1) -0.5
    W2 = np.random.rand(10, 10) - 0.5
    b2 = np.random.rand(10, 1) -0.5
    return W1, b1,W2, b2

def ReLU(Z):
    return np.maximum(0, Z)

def softmax(Z):
    A= np.exp(Z) / sum(np.exp(Z))
    return A
    
def forward_prop(W1, b1, W2, b2, X):
    Z1 = W1.dot(X)+ b1
    A1 =ReLU(Z1)
    Z2 = W2.dot(A1) + b2
    A2 = softmax(Z2)
    return Z1, A1, Z2, A2

def one_hot(Y):
    one_hot_Y= np.zeros((Y.size, Y.max()+1))
    one_hot_Y[np.arange(Y.size), Y]=1
    one_hot_Y = one_hot_Y.T
    return one_hot_Y

def deriv_ReLU(Z):
    return Z>0

def back_prop(Z1, A1,Z2, A2,W1, W2,X, Y):

    one_hot_Y= one_hot(Y)
    dZ2 = A2- one_hot_Y
    dW2= 1/m*dZ2.dot(A1.T)
    db2 = 1/m*np.sum(dZ2)
    dZ1= W2.T.dot(dZ2) * deriv_ReLU(Z1)
    dW1 = 1/m* dZ1.dot(X.T)
    db1 = 1/m*np.sum(dZ1)
    return dW1, db1, dW2, db2

def update_params(W1, b1, W2, b2, dW1,db1, dW2, db2, alpha):
    W1 = W1 -alpha *dW1
    b1 = b1-alpha *db1
    W2 = W2 - alpha * dW2
    b2 = b2 -alpha *db2
    return W1, b1, W2, b2
    

In [7]:
def get_predictions(A2):
    return np.argmax(A2, 0)

def get_accuracy(predictions, Y):
    print(predictions, Y)
    return np.sum(predictions == Y)/Y.size

def gradient_descent(X, Y,alpha, iterations):
    W1, b1, W2, b2 = init_params()
    for i in range(iterations):
        Z1, A1, Z2, A2 = forward_prop(W1, b1, W2, b2, X)
        dW1, db1, dW2, db2 = back_prop(Z1, A1, Z2, A2,W1, W2, X, Y)
        W1, b2, W2, b2 = update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha)
        if i%10 ==0:
            print("Iteration: ", i)
            print("Accuracy: ", get_accuracy(get_predictions(A2), Y))
    return W1, b1, W2, b2

In [8]:
W1, b1, W2, b2 = gradient_descent(X_train, Y_train, 0.10, 500)

Iteration:  0
[9 9 9 ... 7 9 9] [8 4 3 ... 8 0 8]
Accuracy:  0.11097560975609756
Iteration:  10
[9 6 9 ... 2 0 9] [8 4 3 ... 8 0 8]
Accuracy:  0.18192682926829268
Iteration:  20
[9 6 0 ... 2 0 9] [8 4 3 ... 8 0 8]
Accuracy:  0.2822195121951219
Iteration:  30
[3 6 3 ... 2 0 9] [8 4 3 ... 8 0 8]
Accuracy:  0.38009756097560976
Iteration:  40
[8 6 3 ... 2 0 9] [8 4 3 ... 8 0 8]
Accuracy:  0.44390243902439025
Iteration:  50
[8 6 3 ... 2 0 8] [8 4 3 ... 8 0 8]
Accuracy:  0.48965853658536584
Iteration:  60
[8 9 3 ... 8 0 8] [8 4 3 ... 8 0 8]
Accuracy:  0.5254390243902439
Iteration:  70
[8 9 3 ... 8 0 8] [8 4 3 ... 8 0 8]
Accuracy:  0.5590487804878049
Iteration:  80
[8 9 3 ... 8 0 8] [8 4 3 ... 8 0 8]
Accuracy:  0.5915853658536585
Iteration:  90
[8 9 3 ... 8 0 8] [8 4 3 ... 8 0 8]
Accuracy:  0.6193170731707317
Iteration:  100
[8 9 3 ... 8 0 8] [8 4 3 ... 8 0 8]
Accuracy:  0.6436585365853659
Iteration:  110
[8 9 3 ... 8 0 8] [8 4 3 ... 8 0 8]
Accuracy:  0.6667804878048781
Iteration:  120
[8 9 3

In [9]:
def make_predictions(X, W1, b1, W2, b2):
    _, _, _, A2 = forward_prop(W1, b1, W2, b2, X)
    predictions = get_predictions(A2)
    return predictions

def test_prediction(index, W1, b1, W2, b2):
    current_image = X_train[:, index, None]
    prediction = make_predictions(X_train[:, index, None], W1, b1, W2, b2)
    label = Y_train[index]
    print("Prediction: ", prediction)
    print("Label: ", label)
    
    current_image = current_image.reshape((28, 28)) * 255
    plt.gray()
    plt.imshow(current_image, interpolation='nearest')
    plt.show()

In [10]:
dev_predictions = make_predictions(X_dev, W1, b1, W2, b2)
get_accuracy(dev_predictions, Y_dev)

[1 6 7 8 7 4 5 3 7 0 2 5 3 1 4 6 1 1 2 8 9 7 8 6 8 3 3 4 8 2 7 0 4 9 5 5 0
 8 9 8 6 0 3 1 7 4 6 5 4 2 5 8 3 3 8 6 8 4 0 9 2 2 7 8 2 4 0 7 9 3 2 7 6 4
 0 6 8 0 0 2 5 2 3 0 3 6 3 2 5 9 1 6 0 0 9 1 5 9 4 7 3 8 0 8 6 4 8 6 8 9 1
 1 6 9 9 1 8 5 0 4 3 4 4 7 2 9 7 9 5 9 9 0 5 0 4 9 7 1 8 9 0 0 0 2 9 6 7 3
 1 8 2 6 9 8 9 0 1 7 9 9 9 7 4 8 8 6 1 1 0 9 0 9 3 6 7 6 9 1 9 6 6 8 5 0 9
 1 7 6 3 3 2 7 8 8 5 4 2 9 7 8 9 1 6 0 6 1 9 5 4 1 3 1 8 8 0 3 2 2 1 6 4 1
 3 5 0 8 5 3 6 3 5 7 1 2 9 3 6 8 5 4 1 1 6 4 0 3 9 5 9 6 6 4 7 9 1 8 3 1 2
 1 9 4 7 2 0 3 1 7 4 2 1 5 1 4 5 6 8 9 3 2 6 5 7 0 6 4 8 2 1 7 6 0 3 9 8 1
 6 3 8 0 5 3 2 2 8 0 1 3 7 0 6 8 7 5 2 2 3 9 7 1 2 5 2 7 5 4 9 7 2 3 4 7 3
 8 7 8 1 1 4 1 9 7 2 9 8 5 7 4 8 0 1 2 2 8 3 2 0 5 3 1 8 0 9 1 8 0 0 2 1 0
 4 1 6 1 0 2 1 8 3 6 9 8 5 0 2 4 4 1 9 1 8 7 7 6 0 0 9 1 8 9 6 0 4 6 5 1 4
 3 1 4 2 1 2 9 7 8 1 0 9 3 5 0 1 8 3 5 8 7 8 8 0 8 7 1 2 0 4 0 9 6 0 5 4 2
 3 7 8 8 8 4 7 1 7 9 8 0 9 0 2 2 3 2 5 6 7 4 2 3 0 8 6 8 8 5 6 6 1 6 0 8 9
 2 4 1 9 0 9 3 7 9 4 6 8 

0.831